<a href="https://colab.research.google.com/github/nikhilRajput-prog/PyTorch/blob/main/2tensor_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)


2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
        print("GPU is not available")


GPU is available
using GPU: Tesla T4


##Creating a tensor

In [ ]:
#using empty
x=torch.empty(size=(2,3))
y=torch.empty(2,3)
print(x)
print(y)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[       nan,        nan, 6.8664e-44],
        [0.0000e+00, 3.5567e-19, 0.0000e+00]])


In [ ]:
type(x)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#use of seed
torch.rand(4,3)

tensor([[0.7146, 0.4201, 0.3070],
        [0.7398, 0.1604, 0.1648],
        [0.2539, 0.2639, 0.4838],
        [0.9953, 0.2730, 0.5757]])

In [ ]:
#manual seed same random number every time
torch.manual_seed(100)
torch.rand(4,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
torch.tensor([[1,2,3],[3,4,2]])

tensor([[1, 2, 3],
        [3, 4, 2]])

In [ ]:
#other way
#using arange
print("using arange->", torch.arange(0,18,2))

using arange-> tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])


In [ ]:
#using linspace
print("using linespace->", torch.linspace(0,20,20))

using linespace-> tensor([ 0.0000,  1.0526,  2.1053,  3.1579,  4.2105,  5.2632,  6.3158,  7.3684,
         8.4211,  9.4737, 10.5263, 11.5789, 12.6316, 13.6842, 14.7368, 15.7895,
        16.8421, 17.8947, 18.9474, 20.0000])


In [ ]:
#using eye
print("using eye->", torch.eye(4))

using eye-> tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [ ]:
#using full
print("using full-> ", torch.full((3,3),4))

using full->  tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])


##Tensor Shape

In [ ]:
x=torch.tensor([[1,2,3],[1,2,2]])
print(x)
x.shape

tensor([[1, 2, 3],
        [1, 2, 2]])


torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
#torch.rand_like(x) not work due to x has int and rand has [0,1]
torch.rand_like(x,dtype=torch.float64)

tensor([[0.6941, 0.3464, 0.9751],
        [0.7911, 0.4274, 0.4460]], dtype=torch.float64)

##Tensor Datatype

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1,2,2,2.0, 2.1], dtype=torch.int32)

tensor([1, 2, 2, 2, 2], dtype=torch.int32)

In [ ]:
torch.tensor([[2,2],[2,5]], dtype=torch.float64)

tensor([[2., 2.],
        [2., 5.]], dtype=torch.float64)

##Operation

In [ ]:
x=torch.rand(2,2)
print(x)
x+2


tensor([[0.4440, 0.9478],
        [0.7445, 0.4892]])


tensor([[2.4440, 2.9478],
        [2.7445, 2.4892]])

In [ ]:
x-2
x*2
x/2
(x*100)/2#float
(x*100)//2 #int


tensor([[22., 47.],
        [37., 24.]])

In [ ]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)
x+y

tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])
tensor([[0.7909, 0.4235],
        [0.0169, 0.2209]])


tensor([[1.0334, 1.1238],
        [0.5446, 0.4681]])

In [ ]:
torch.abs(x)

tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])

In [ ]:
torch.neg(x)

tensor([[-0.2426, -0.7003],
        [-0.5277, -0.2472]])

In [ ]:
torch.ceil(x)
torch.floor(x)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.clamp(x,min=0.2,max=0.7)

tensor([[0.2426, 0.7000],
        [0.5277, 0.2472]])

In [ ]:
e=torch.randint(size=(2,3), low=0, high=100, dtype=torch.float32)
e

tensor([[15., 39., 29.],
        [47., 25., 89.]])

In [ ]:
torch.sum(e)

tensor(198)

In [ ]:
torch.sum(e, dim=0)

tensor([33, 94, 71])

In [ ]:
torch.sum(e,dim=1)

tensor([116,  82])

In [ ]:
torch.mean(e) # work only in float

tensor(40.6667)

In [ ]:
torch.mean(e, dim=0)

tensor([31., 32., 59.])

In [ ]:
torch.median(e)

tensor(29.)

In [ ]:
torch.max(e)

tensor(89.)

In [ ]:
torch.min(e)

tensor(15.)

In [ ]:
torch.argmax(e)

tensor(5)

##matrix operation

In [ ]:
f=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
g=torch.randint(size=(3,2), low=0, high=10, dtype=torch.float32)
print(f)
print(g)
torch.matmul(f,g)

tensor([[5., 5., 0.],
        [4., 3., 8.]])
tensor([[8., 3.],
        [3., 5.],
        [0., 6.]])


tensor([[55., 40.],
        [41., 75.]])

In [ ]:
a=torch.tensor([3,4])
b=torch.tensor([3,3])
torch.dot(a,b)

tensor(21)

In [ ]:
torch.transpose(f, 1,0)

tensor([[5., 4.],
        [5., 3.],
        [0., 8.]])

In [ ]:
f.T

tensor([[5., 4.],
        [5., 3.],
        [0., 8.]])

In [ ]:
a=torch.tensor([[24,2.0],[5,5.0]])
torch.det(x)

tensor(-0.3096)

In [ ]:
torch.inverse(a)

tensor([[ 0.0455, -0.0182],
        [-0.0455,  0.2182]])

In [ ]:
f=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
g=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [ ]:
f>g


tensor([[ True, False,  True],
        [False,  True, False]])

In [ ]:
torch.log(f)

tensor([[1.3863,   -inf, 2.0794],
        [1.3863, 1.9459, 0.6931]])

In [ ]:
torch.sqrt(g)

tensor([[1.7321, 2.8284, 2.2361],
        [2.4495, 1.4142, 3.0000]])

In [ ]:
torch.sigmoid(f)

tensor([[0.9820, 0.5000, 0.9997],
        [0.9820, 0.9991, 0.8808]])

In [ ]:
torch.softmax(f, dim=0)

tensor([[5.0000e-01, 9.1105e-04, 9.9753e-01],
        [5.0000e-01, 9.9909e-01, 2.4726e-03]])

In [ ]:
torch.relu(f)

tensor([[4., 0., 8.],
        [4., 7., 2.]])

##inplace operation

In [ ]:
m=torch.rand(2,4)
n=torch.rand(2,4)
print(m)
print(n)

tensor([[0.9516, 0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393, 0.2243]])
tensor([[0.8935, 0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131, 0.3957]])


In [ ]:
m.add_(n)

tensor([[1.8451, 0.3353, 0.4104, 1.2152],
        [0.9561, 1.0845, 0.6525, 0.6199]])

In [ ]:
m

tensor([[1.8451, 0.3353, 0.4104, 1.2152],
        [0.9561, 1.0845, 0.6525, 0.6199]])

In [ ]:
m=m+n

In [ ]:
m

tensor([[2.7386, 0.3850, 0.5884, 1.5163],
        [1.1454, 2.0031, 0.8656, 1.0156]])

In [ ]:
m.relu_()

tensor([[2.7386, 0.3850, 0.5884, 1.5163],
        [1.1454, 2.0031, 0.8656, 1.0156]])

underscore made the inplace operation

##copying a tensor

In [ ]:
a=torch.tensor([[1,2],[5,3]])

In [ ]:
b=a
print(id(a))
print(id(b))

134477388448544
134477388448544


In [ ]:
b=a.clone()# b take new memory
print(id(a))
print(id(b))

134477388448544
134477385392016


##Tensor operation on gpu

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda')

In [ ]:
torch.rand((2,3), device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
a=torch.rand(2,4)
a

tensor([[0.6017, 0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079, 0.6269]])

In [ ]:
b=a.to(device)

tensor([[0.6017, 0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079, 0.6269]], device='cuda:0')

In [ ]:
b+5 # run on gpu

tensor([[ 6,  7],
        [10,  8]])

In [ ]:
import time
import torch

size = 2000  # start smaller (10000 may crash memory)

a = torch.rand(size, size)
b = torch.rand(size, size)

# ---------------- CPU ----------------
start = time.time()
torch.matmul(a, b)
end = time.time()

cpu_time = end - start
print(f"CPU time: {cpu_time:.4f} sec")

# ---------------- GPU ----------------
if torch.cuda.is_available():
    c = a.to('cuda')
    d = b.to('cuda')

    # warm-up
    torch.matmul(c, d)
    torch.cuda.synchronize()

    start = time.time()
    torch.matmul(c, d)
    torch.cuda.synchronize()
    end = time.time()

    gpu_time = end - start
    print(f"GPU time: {gpu_time:.4f} sec")

    # speedup
    print(f"Speedup (CPU/GPU): {cpu_time / gpu_time:.2f}x")

else:
    print("GPU not available")

CPU time: 0.2046 sec
GPU time: 0.0060 sec
Speedup (CPU/GPU): 34.10x


##Reshaping

In [ ]:
a=torch.ones(4,4)

In [ ]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
print(b)
b.permute(2,1,0)


tensor([[[0.4099, 0.2754, 0.3221, 0.6855],
         [0.8789, 0.2204, 0.4462, 0.1002],
         [0.4717, 0.4898, 0.6537, 0.7417]],

        [[0.0565, 0.5975, 0.3761, 0.6005],
         [0.4849, 0.6444, 0.3537, 0.1182],
         [0.6562, 0.5510, 0.6434, 0.8568]]])


tensor([[[0.4099, 0.0565],
         [0.8789, 0.4849],
         [0.4717, 0.6562]],

        [[0.2754, 0.5975],
         [0.2204, 0.6444],
         [0.4898, 0.5510]],

        [[0.3221, 0.3761],
         [0.4462, 0.3537],
         [0.6537, 0.6434]],

        [[0.6855, 0.6005],
         [0.1002, 0.1182],
         [0.7417, 0.8568]]])

In [ ]:
c=torch.rand(223,223,3)
c.unsqueeze(2).shape#add dimension

torch.Size([223, 223, 1, 3])

In [ ]:
d=torch.rand(20,1)
d.squeeze(1).shape

torch.Size([20])

##Numpy and pytorch

In [ ]:
import numpy as np
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b=a.numpy()
b

array([1, 2, 3])

In [ ]:
torch.from_numpy(b)


tensor([1, 2, 3])